# Generated by Django 4.2.1 on 2023-05-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotton',
            name='cotton',
            field=models.FileField(null=True, upload_to='cotton/'),
        ),
        migrations.AlterField(
            model_name='potato',
            name='potato',
            field=models.FileField(null=True, upload_to='potato/'),
        ),
        migrations.AlterField(
            model_name='tomato',
            name='tomato',
            field=models.FileField(null=True, upload_to='tomato/'),
        ),
    ]
